// ملف build.gradle (الرئيسي - Root)
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // تعريف إصدار محرك أندرويد المتوافق مع جافا 21 وجرادل 9
        classpath 'com.android.tools.build:gradle:8.7.0'
    }
}

// هذه المهمة لتنظيف المجلدات المؤقتة عند بناء المشروع من جديد
task clean(type: Delete) {
    delete rootProject.buildDir
}
